# Generated by Django 6.0.1 on 2026-02-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
            preserve_default=False,
        ),
    ]
