# Generated by Django 6.0.1 on 2026-02-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_hall_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
