# Generated by Django 6.0.1 on 2026-03-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_hall_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='exam',
        ),
    ]
