# Generated by Django 6.0.3 on 2026-04-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_hall_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invigilator',
            name='halls',
        ),
        migrations.AddField(
            model_name='invigilator',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=20)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.invigilator')),
            ],
        ),
    ]
