# Generated by Django 6.0.3 on 2026-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_invigilator_halls_invigilator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallassignment',
            name='session',
            field=models.CharField(max_length=10),
        ),
    ]
